services:
  postgres:
    image: postgres:15-alpine
    container_name: city_explorer_postgres_prod
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${POSTGRES_PORT_PROD}:5432"
    volumes:
      - ./docker/postgres/prod_data:/var/lib/postgresql/data
    networks:
      - city_explorer_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          memory: 128M

  backend:
    container_name: city_explorer_csharp_prod
    image: ghcr.io/klaudiuszsoltysik/city-explorer/backend:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__PostgresConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - GoogleAuth__ClientId=${GOOGLE_AUTH_CLIENT_ID}
      - JwtSettings__SecretKey=${JWT_SECTRET_KEY}
      - JwtSettings__Issuer=CityExplorerBackend
      - JwtSettings__Audience=CityExplorerApp
      - ApiKey=QfhciAu72jYOX3Wo8gxRnTddj8QYN3Rc
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - city_explorer_net
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          memory: 256M

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: city_explorer_tunnel
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - city_explorer_net
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  watchtower:
    image: containrrr/watchtower
    container_name: city_explorer_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup city_explorer_csharp_prod
    environment:
      - DOCKER_API_VERSION=1.45
    networks:
      - city_explorer_net
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  portainer:
    image: portainer/portainer-ce:latest
    container_name: city_explorer_dashboard
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - city_explorer_net
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  data-processor:
    build: ./python
    container_name: python_data_processor
    profiles: ["tools"]
    volumes:
      - ./python/raw_data:/app/raw_data
      - ./python/processed_data:/app/processed_data
    environment:
      - DB_CONNECTION_STRING=host=postgres dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD}
      - INPUT_DIRECTORY=/app/raw_data
      - OUTPUT_DIRECTORY=/app/processed_data
    networks:
      - city_explorer_net
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  postgres-backup:
    image: prodrigestivill/postgres-backup-local
    container_name: city_explorer_postgres_backup
    user: postgres:postgres
    volumes:
      - ./backups:/backups
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SCHEDULE=@every 12h00m
      - BACKUP_KEEP_DAYS=7
    networks:
      - city_explorer_net
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  city_explorer_net:
    driver: bridge

volumes:
  postgres_data:
  portainer_data:
