FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app

WORKDIR /app/src

EXPOSE 8080

ENTRYPOINT ["dotnet", "watch", "run", "--project", "csharp.csproj", "--no-launch-profile", "--urls", "http://+:8080"]