name: Build and publish Android APK

on:
  push:
    branches: ["master"]
    paths:
      - "kotlin/**"
      - ".github/workflows/kotlin_deploy.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kotlin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: city-explorer
          path: kotlin/app/build/outputs/apk/release/city-explorer.apk
